name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install sitemap generator
        run: npm install -g sitemap-generator-cli

      - name: Generate Sitemap
        run: sitemap-generator https://nocountry.studio -o sitemap.xml -l

      - name: Set up SSH for git push
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_GENERATE_SITEMAP }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global url."git@github.com:".insteadOf "https://github.com/"
        env:
          GITHUB_SSH_PRIVATE_KEY: ${{ secrets.SSH_GENERATE_SITEMAP }}

      - name: Commit and Push the Sitemap
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          if git diff --cached --exit-code; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "auto-generated sitemap"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}